### ISSUE TITLE
Quoted keyword

### ISSUE THREAD

**Issue by 2kaud** [m-peko/booleval#38]
A quoted keyword is considered an invalid expression

obj pass("and", 123);
...
evaluator.expression("field_a \"and\" and field_b 123");

should be valid as "and" is a literal and not a keyword - but is considered a keyword and rejected as an invalid expression.

**Comment by m-peko** [comment]
Issue is fixed by using split iterators instead of returning `std::vector` from `split` function. Also, new unit test is added to cover this specific case when having a keyword as a field value.
