### ISSUE TITLE
Allow quoted strings in expressions

### ISSUE THREAD

**Issue by jamesattewell** [m-peko/booleval#47]
This code is awesome and exactly what I was looking for, thanks for developing and sharing @m-peko 

The one thing that is missing, or I can't seem to get to work, is being able to quote string constants. 
i.e.  field_name == 'string with spaces'

Is there a way to do this currently or is this feature planned?

**Comment by m-peko** [comment]
Hi @jamesattewell,

I am glad you like my library. This feature is already supported. You just need to to specify the expression like `field_name \"string with spaces\"`.

Let me know if this has helped you.

**Comment by m-peko** [comment]
FYI, here is one of the unit tests that shows this funcionality:

```cpp
TEST_F(EvaluatorTest, EqualToOperatorMultipleWords) {
    obj<std::string> foo{ "foo foo" };
    obj<std::string> bar{ "bar bar" };

    booleval::evaluator evaluator({
        { "field_a", &obj<std::string>::value_a }
    });

    EXPECT_TRUE(evaluator.expression("field_a \"foo foo\""));
    EXPECT_TRUE(evaluator.is_activated());
    EXPECT_TRUE(evaluator.evaluate(foo));
    EXPECT_FALSE(evaluator.evaluate(bar));
}
```

**Comment by jamesattewell** [comment]
Thanks Marin.

I had tried this but I was getting false returned when evaluating the expression. I have had a play around today and it does work but there is a problem with parentheses around the expression when using the quotes. 

This fails:-
    `auto valid = evaluator.expression("(fieldString \"foo foo\")");`

but adding a space before the closing parentheses works:-
    `auto valid = evaluator.expression("(fieldString \"foo foo\" )");`

Also, is there any chance of being able to use 'single quotes' around the string as well?

Thanks for the help

James

**Comment by m-peko** [comment]
In case you want to use single quotes, you can change the line 78 in _tokenizer.cpp_ file from:

```c++
auto tokens_range = utils::split_range<options>(expression_, delims);
```

to

```c++
auto tokens_range = utils::split_range<options, utils::single_quote_char>(expression_, delims);
```

Now, it should work with single quotes too.

Regarding this hacky workaround about adding a space before the closing parentheses, it must be a small bug in `split_range` class. Let me take a deeper look at it and I will get back to you.

Thanks for reporting this and feel free to contribute.

**Comment by jamesattewell** [comment]
Hi Marin,

I think I have found the issue but I haven't run all of your tests to make sure it doesn't break anything else so please verify its not broken something else. 

The change I have made is in split_range::constexpr iterator& operator++() noexcept (split_range.hpp, line 105) from this:-
`prev_ = std::next(curr_);`
to this:-
`prev_ = skip_char(curr_, whitespace_char);`

As it seemed to always be eating the character after the closing quote.

**Comment by m-peko** [comment]
Hi @jamesattewell,

I think you are right with a small modification. We need to take into account if the delimiters need to be included or not so the following needs to be changed (starting from line 104, _split_range.hpp_):

```c++
if (std::end(strv_) != curr_) {
      prev_ = std::next(curr_);
      if constexpr (is_set(iter_options, split_options::include_delimiters)) {
             prev_ = skip_char(curr_, whitespace_char);
      }
}
```

**Comment by m-peko** [comment]
Hi @jamesattewell 

I have merged the fix into the master. Please verify that this works for you and let me know.
Thank you once again on reporting this issue and feel free to contribute in future. I am looking for contributors to this project.

Thanks and best regard,
Marin

**Comment by jamesattewell** [comment]
I have tested the new code here and it all works for me. Thanks for the help.
