### ISSUE TITLE
Missing class initializers

### ISSUE THREAD

**Issue by jamesattewell** [m-peko/booleval#50]
Hi Marin,

There are a few classes that are missing class initializers. I will submit a pull request for this shortly.

Cheers

James

**Comment by m-peko** [comment]
Hi James,

As I commented out, default constructors of complex data members are called automatically so no need to explicitly list them in initialization list.

Cheers,
Marin

**Comment by jamesattewell** [comment]
Hi Marin,

Yes, I only added the complex ones for completeness. However, the evaluator::evaluator(field_map const& fields) constructor does need to set is_activated_ as this is only a bool. Do you want me to adjust the pull request to only fix that one?

Cheers

James

**Comment by m-peko** [comment]
Yes, you are right there. Please adjust the PR and I will merge it.

Thanks
