### ISSUE TITLE
Custom booleval exceptions and handling field null/invalid conditions

### ISSUE THREAD

**Issue by jamesattewell** [m-peko/booleval#51]
Hi Marin,

I have some evaluator fields which can sometimes not be available (be null) and it would be good if there was a clean way to handle this. I have been experimenting with ways to do this and the easiest solution I have come up with is to allow the evaluator field_map functions to throw a specialised booleval exception (based on std::exception or std::runtime_error) i.e. booleval_field_null. We could catch this new booleval_field_null exception in result_visitor.visit_relational() and then rethrow with more context (i.e. name of the field) and then it can be caught by the code that calls evaluator.evaluate() (outside of booleval code) and handled/logged there.

There is also an unhandled exception in result_visitor.visit_relational if key.value() is not found in the fields_ map which could also throw an booleval_field_unknown exception.

Do you have any thoughts on this? 

Cheers

James

**Comment by m-peko** [comment]
Hi James,

Can you please show me an example of such expression, that would lead to throwing an exception?

Thanks,
Marin

**Comment by jamesattewell** [comment]
Hi Marin,

If I use any expression where the named field does not exist in the field map passed to the evaluator, I am seeing a std::bad_function_call unhandled exception in Visual Studio from any_mem_fn::invoke() call.

Cheers

James

**Comment by m-peko** [comment]
Ok, I get your point. It will be implemented ASAP.

**Comment by m-peko** [comment]
@jamesattewell pls check PR #53 and let me know if that's what you are requesting. 

Thanks,
Marin

**Comment by jamesattewell** [comment]
@m-peko Yep, that's it, thanks for sorting ;)

I can have a look at the other part of my request above (throwing exceptions from the field map functions passed in to the evaluator class).

Cheers

James

**Comment by m-peko** [comment]
Sure, give it a try. I will merge PR #53

**Comment by m-peko** [comment]
@jamesattewell can we close this issue now?

**Comment by jamesattewell** [comment]
@m-peko I think so. Although there is one potential issue I did notice after it was merged, are we now doing two lookups in the fields_ std::map in visit_relational()?

template <typename T, typename F>
[[nodiscard]] constexpr bool visit_relational(tree_node const& node, T const& obj, F&& func) {
    auto key = node.left->token;
    auto value = node.right->token;

    if (fields_.find(key.value()) == std::end(fields_)) {
        throw field_not_found(key.value());
    }

    return func(fields_[key.value()].invoke(obj), value.value());
}

**Comment by m-peko** [comment]
Yes, that's true. You can fix it if you want.

**Comment by jamesattewell** [comment]
Cool, I will give it a go. I have fixed it once before but it failed in CLang CI build, something to do with std::map iterator not being able to be used in a constexpr. I will submit a pull request shortly and try and sort it.

Go ahead and close this issue now

**Comment by m-peko** [comment]
@jamesattewell Hi James, I am in a process of refactoring this library and I would like to remove exceptions. What do you think about evaluator just return false in case there is an unknown field. Would you, as the library user, be satisfied with this?

**Comment by jamesattewell** [comment]
@m-peko Hi Marin. The exceptions have proved to be very handy to me when debugging why an expression is not working, especially knowing when a field is not found. 

We are using booleval expressions that are entered by the user in JSON configurations files so being able to give them the information about what is wrong when it fails is valuable. From your description, this would become invisible I presume?

The code we are using is in my develop branch here, this has exceptions implemented https://github.com/jamesattewell/booleval/tree/develop

**Comment by m-peko** [comment]
I see.

Yes, this would be invisible. Might be that I leave exceptions at the end. Thanks for your opinion!
Btw if you have any other feature request, I would be glad to hear about it.
