### ISSUE TITLE
Question: Set operations

### ISSUE THREAD

**Issue by Patick-Bateman** [m-peko/booleval#63]
Is it possible to implement set operations (intersection/etc) for the current implementation? If so, how would they look?
I suppose each set will be represented as a balanced subtree? Thx.

**Comment by m-peko** [comment]
Hi @Patick-Bateman ,

Can you please give me an example of such expression and what would be the expected output?

Tnx

**Comment by Patick-Bateman** [comment]
@m-peko Sure, syntax may vary (im going to use `in` keyword), i'm especially interested in only one operation - intersection.
1. Numbers intersection, `field_a` can either be number or list of numbers `[1, 2, 3]` - `field_a in [1, 2, 3, 4, 5]` -> true/false
2. Strings intersection, `field_a` can either be string or list of string `["1", "2", "3"]` - `field_a in ["1" , "2", "3", "4", "5"]` -> true/false.

**Comment by m-peko** [comment]
@Patick-Bateman ok, i see. This is possible and it can be done as the next bigger feature. Do you want to work it out yourself? I am looking for contributors

**Comment by Patick-Bateman** [comment]
@m-peko I can try, but you got any vision how this is possibly can be implemented? I will be glad to hear that.

**Comment by m-peko** [comment]
Great, sure.

The example you have mentioned `[1, 2, 3]` - `field_a in [1, 2, 3, 4, 5]` is not an intersection though, because intersection would mean following is also true: `[1, 2, 6]` - `field_a in [1, 2, 3, 4, 5]`. I think you don't want this, right?

You rather need "contains" operator?

What are the other operations you need to implement?

**Comment by Patick-Bateman** [comment]
@m-peko No, I'm really meant intersection, probably my examples aren't that great. I need only this operation basically. More examples (using & as operator):

`[1, 2, 3] & [1]` -> `[1]` ->`true`

`["a", "b", "c"] & ["a", "x", "c"] `-> `["a", "c"]` -> `true`

`[1, 2, 3] & [4]` -> `[]` -> `false`

But if it's really problematic to implement or it's will not be a great fit for the library, i'm fine with "contains" alternative.

**Comment by m-peko** [comment]
Ok, I see. I think it would be easier to implement `contains` in the first run. Then we can continue with other operators.

What you need to do is:
- add new token types like `[`, `]` and `in`
- enable constructing `any_value` from an iterable by stringifying it
- comparison

**Comment by m-peko** [comment]
Will close it due to inactivity. If you are still interested in this, please reopen it.
